/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ["class"],
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    50: "hsl(var(--primary-50))",
                    100: "hsl(var(--primary-100))",
                    200: "hsl(var(--primary-200))",
                    300: "hsl(var(--primary-300))",
                    400: "hsl(var(--primary-400))",
                    500: "hsl(var(--primary-500))",
                    600: "hsl(var(--primary-600))",
                    700: "hsl(var(--primary-700))",
                    800: "hsl(var(--primary-800))",
                    900: "hsl(var(--primary-900))",
                    950: "hsl(var(--primary-950))",
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    50: "hsl(var(--destructive-50))",
                    100: "hsl(var(--destructive-100))",
                    200: "hsl(var(--destructive-200))",
                    300: "hsl(var(--destructive-300))",
                    400: "hsl(var(--destructive-400))",
                    500: "hsl(var(--destructive-500))",
                    600: "hsl(var(--destructive-600))",
                    700: "hsl(var(--destructive-700))",
                    800: "hsl(var(--destructive-800))",
                    900: "hsl(var(--destructive-900))",
                    950: "hsl(var(--destructive-950))",
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
                success: {
                    50: "hsl(var(--success-50))",
                    100: "hsl(var(--success-100))",
                    200: "hsl(var(--success-200))",
                    300: "hsl(var(--success-300))",
                    400: "hsl(var(--success-400))",
                    500: "hsl(var(--success-500))",
                    600: "hsl(var(--success-600))",
                    700: "hsl(var(--success-700))",
                    800: "hsl(var(--success-800))",
                    900: "hsl(var(--success-900))",
                    950: "hsl(var(--success-950))",
                    DEFAULT: "hsl(var(--success))",
                    foreground: "hsl(var(--success-foreground))",
                },
                warning: {
                    50: "hsl(var(--warning-50))",
                    100: "hsl(var(--warning-100))",
                    200: "hsl(var(--warning-200))",
                    300: "hsl(var(--warning-300))",
                    400: "hsl(var(--warning-400))",
                    500: "hsl(var(--warning-500))",
                    600: "hsl(var(--warning-600))",
                    700: "hsl(var(--warning-700))",
                    800: "hsl(var(--warning-800))",
                    900: "hsl(var(--warning-900))",
                    950: "hsl(var(--warning-950))",
                    DEFAULT: "hsl(var(--warning))",
                    foreground: "hsl(var(--warning-foreground))",
                },
                info: {
                    50: "hsl(var(--info-50))",
                    100: "hsl(var(--info-100))",
                    200: "hsl(var(--info-200))",
                    300: "hsl(var(--info-300))",
                    400: "hsl(var(--info-400))",
                    500: "hsl(var(--info-500))",
                    600: "hsl(var(--info-600))",
                    700: "hsl(var(--info-700))",
                    800: "hsl(var(--info-800))",
                    900: "hsl(var(--info-900))",
                    950: "hsl(var(--info-950))",
                    DEFAULT: "hsl(var(--info))",
                    foreground: "hsl(var(--info-foreground))",
                },
                brand: {
                    50: "hsl(var(--brand-50))",
                    100: "hsl(var(--brand-100))",
                    200: "hsl(var(--brand-200))",
                    300: "hsl(var(--brand-300))",
                    400: "hsl(var(--brand-400))",
                    500: "hsl(var(--brand-500))",
                    600: "hsl(var(--brand-600))",
                    700: "hsl(var(--brand-700))",
                    800: "hsl(var(--brand-800))",
                    900: "hsl(var(--brand-900))",
                    950: "hsl(var(--brand-950))",
                    DEFAULT: "hsl(var(--brand))",
                    foreground: "hsl(var(--brand-foreground))",
                    muted: "hsl(var(--brand-muted))",
                    "muted-foreground": "hsl(var(--brand-muted-foreground))",
                    subtle: "hsl(var(--brand-subtle))",
                },
                sidebar: {
                    DEFAULT: "hsl(var(--sidebar))",
                    foreground: "hsl(var(--sidebar-foreground))",
                    border: "hsl(var(--sidebar-border))",
                    accent: "hsl(var(--sidebar-accent))",
                    "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
                btn: "var(--radius-btn)",
                "btn-sm": "var(--radius-btn-sm)",
                input: "var(--radius-input)",
                card: "var(--radius-card)",
                badge: "var(--radius-badge)",
            },
            spacing: {
                "control-sm": "var(--size-control-sm)",
                control: "var(--size-control)",
                "control-lg": "var(--size-control-lg)",
            },
            height: {
                "control-sm": "var(--size-control-sm)",
                control: "var(--size-control)",
                "control-lg": "var(--size-control-lg)",
            },
            width: {
                "control-sm": "var(--size-control-sm)",
                control: "var(--size-control)",
                "control-lg": "var(--size-control-lg)",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
