/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as PortalRouteRouteImport } from "./routes/_portal/route";
import { Route as PortalIndexRouteImport } from "./routes/_portal/index";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup";
import { Route as AuthSigninRouteImport } from "./routes/auth/signin";
import { Route as PortalWatchRouteImport } from "./routes/_portal/watch";
import { Route as PortalTrendingRouteImport } from "./routes/_portal/trending";
import { Route as PortalTermsRouteImport } from "./routes/_portal/terms";
import { Route as PortalTagsRouteImport } from "./routes/_portal/tags";
import { Route as PortalSearchRouteImport } from "./routes/_portal/search";
import { Route as PortalPrivacyRouteImport } from "./routes/_portal/privacy";
import { Route as PortalMembersRouteImport } from "./routes/_portal/members";
import { Route as PortalLatestRouteImport } from "./routes/_portal/latest";
import { Route as PortalFeaturedRouteImport } from "./routes/_portal/featured";
import { Route as PortalExploreRouteImport } from "./routes/_portal/explore";
import { Route as PortalCookiesRouteImport } from "./routes/_portal/cookies";
import { Route as PortalBrowseRouteImport } from "./routes/_portal/browse";
import { Route as PortalAboutRouteImport } from "./routes/_portal/about";
import { Route as PortalHandleRouteImport } from "./routes/_portal/$handle";
import { Route as AuthenticatedSettingsRouteImport } from "./routes/_authenticated/settings";
import { Route as AuthenticatedAdminRouteImport } from "./routes/_authenticated/admin";
import { Route as AuthenticatedPortalRouteImport } from "./routes/_authenticated/_portal";
import { Route as PortalHandleIndexRouteImport } from "./routes/_portal/$handle/index";
import { Route as AuthenticatedAdminIndexRouteImport } from "./routes/_authenticated/admin/index";
import { Route as PortalUIdRouteImport } from "./routes/_portal/u.$id";
import { Route as PortalPlaylistTokenRouteImport } from "./routes/_portal/playlist.$token";
import { Route as PortalPSlugRouteImport } from "./routes/_portal/p.$slug";
import { Route as PortalCIdRouteImport } from "./routes/_portal/c.$id";
import { Route as PortalHandleSplatRouteImport } from "./routes/_portal/$handle/$";
import { Route as AuthenticatedSettingsProfileRouteImport } from "./routes/_authenticated/settings.profile";
import { Route as AuthenticatedSettingsPreferencesRouteImport } from "./routes/_authenticated/settings.preferences";
import { Route as AuthenticatedSettingsPasswordRouteImport } from "./routes/_authenticated/settings.password";
import { Route as AuthenticatedSettingsAppearanceRouteImport } from "./routes/_authenticated/settings.appearance";
import { Route as AuthenticatedAdminUsersRouteImport } from "./routes/_authenticated/admin/users";
import { Route as AuthenticatedAdminTranscodingRouteImport } from "./routes/_authenticated/admin/transcoding";
import { Route as AuthenticatedAdminTagsRouteImport } from "./routes/_authenticated/admin/tags";
import { Route as AuthenticatedAdminStyleGuideRouteImport } from "./routes/_authenticated/admin/style-guide";
import { Route as AuthenticatedAdminSettingsRouteImport } from "./routes/_authenticated/admin/settings";
import { Route as AuthenticatedAdminReviewRouteImport } from "./routes/_authenticated/admin/review";
import { Route as AuthenticatedAdminPromotionRouteImport } from "./routes/_authenticated/admin/promotion";
import { Route as AuthenticatedAdminPortalRouteImport } from "./routes/_authenticated/admin/portal";
import { Route as AuthenticatedAdminPlaylistsRouteImport } from "./routes/_authenticated/admin/playlists";
import { Route as AuthenticatedAdminPermissionsRouteImport } from "./routes/_authenticated/admin/permissions";
import { Route as AuthenticatedAdminPaymentRouteImport } from "./routes/_authenticated/admin/payment";
import { Route as AuthenticatedAdminNotificationsRouteImport } from "./routes/_authenticated/admin/notifications";
import { Route as AuthenticatedAdminLiveRoomsRouteImport } from "./routes/_authenticated/admin/live-rooms";
import { Route as AuthenticatedAdminDrmRouteImport } from "./routes/_authenticated/admin/drm";
import { Route as AuthenticatedAdminContentStructureRouteImport } from "./routes/_authenticated/admin/content-structure";
import { Route as AuthenticatedAdminCommentsRouteImport } from "./routes/_authenticated/admin/comments";
import { Route as AuthenticatedAdminChannelsRouteImport } from "./routes/_authenticated/admin/channels";
import { Route as AuthenticatedAdminCategoriesRouteImport } from "./routes/_authenticated/admin/categories";
import { Route as AuthenticatedAdminAdsRouteImport } from "./routes/_authenticated/admin/ads";
import { Route as AuthenticatedPortalSubscriptionsRouteImport } from "./routes/_authenticated/_portal/subscriptions";
import { Route as AuthenticatedPortalNotificationsRouteImport } from "./routes/_authenticated/_portal/notifications";
import { Route as AuthenticatedAdminMediaRouteRouteImport } from "./routes/_authenticated/admin/media/route";
import { Route as AuthenticatedAdminArticlesRouteRouteImport } from "./routes/_authenticated/admin/articles/route";
import { Route as AuthenticatedPortalMeRouteRouteImport } from "./routes/_authenticated/_portal/me/route";
import { Route as AuthenticatedPortalArticlesRouteRouteImport } from "./routes/_authenticated/_portal/articles/route";
import { Route as AuthenticatedAdminMediaIndexRouteImport } from "./routes/_authenticated/admin/media/index";
import { Route as AuthenticatedAdminArticlesIndexRouteImport } from "./routes/_authenticated/admin/articles/index";
import { Route as AuthenticatedPortalMeIndexRouteImport } from "./routes/_authenticated/_portal/me/index";
import { Route as AuthenticatedPortalArticlesIndexRouteImport } from "./routes/_authenticated/_portal/articles/index";
import { Route as AuthenticatedAdminTranscodingStatusRouteImport } from "./routes/_authenticated/admin/transcoding.status";
import { Route as AuthenticatedAdminTranscodingProfilesRouteImport } from "./routes/_authenticated/admin/transcoding.profiles";
import { Route as AuthenticatedAdminMediaIdRouteImport } from "./routes/_authenticated/admin/media/$id";
import { Route as AuthenticatedAdminArticlesNewRouteImport } from "./routes/_authenticated/admin/articles/new";
import { Route as AuthenticatedPortalMeVideosRouteImport } from "./routes/_authenticated/_portal/me/videos";
import { Route as AuthenticatedPortalMeUploadRouteImport } from "./routes/_authenticated/_portal/me/upload";
import { Route as AuthenticatedPortalMeStyleGuideRouteImport } from "./routes/_authenticated/_portal/me/style-guide";
import { Route as AuthenticatedPortalMePlaylistsRouteImport } from "./routes/_authenticated/_portal/me/playlists";
import { Route as AuthenticatedPortalMeNotificationsRouteImport } from "./routes/_authenticated/_portal/me/notifications";
import { Route as AuthenticatedPortalMeHistoryRouteImport } from "./routes/_authenticated/_portal/me/history";
import { Route as AuthenticatedPortalMeFavoritesRouteImport } from "./routes/_authenticated/_portal/me/favorites";
import { Route as AuthenticatedPortalMeChannelsRouteImport } from "./routes/_authenticated/_portal/me/channels";
import { Route as AuthenticatedPortalMeChannelRouteImport } from "./routes/_authenticated/_portal/me/channel";
import { Route as AuthenticatedPortalArticlesSlugRouteImport } from "./routes/_authenticated/_portal/articles.$slug";
import { Route as AuthenticatedPortalMeArticlesRouteRouteImport } from "./routes/_authenticated/_portal/me/articles/route";
import { Route as AuthenticatedPortalMeArticlesIndexRouteImport } from "./routes/_authenticated/_portal/me/articles/index";
import { Route as AuthenticatedAdminArticlesIdEditRouteImport } from "./routes/_authenticated/admin/articles/$id.edit";
import { Route as AuthenticatedPortalMediaShortTokenEditRouteImport } from "./routes/_authenticated/_portal/media.$shortToken.edit";
import { Route as AuthenticatedPortalMeArticlesNewRouteImport } from "./routes/_authenticated/_portal/me/articles.new";
import { Route as AuthenticatedPortalMeArticlesTokenEditRouteImport } from "./routes/_authenticated/_portal/me/articles.$token.edit";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: "/_portal",
  getParentRoute: () => rootRouteImport,
} as any);
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PortalRouteRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/auth/signup",
  path: "/auth/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: "/auth/signin",
  path: "/auth/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const PortalWatchRoute = PortalWatchRouteImport.update({
  id: "/watch",
  path: "/watch",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalTrendingRoute = PortalTrendingRouteImport.update({
  id: "/trending",
  path: "/trending",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalTermsRoute = PortalTermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalTagsRoute = PortalTagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalSearchRoute = PortalSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalPrivacyRoute = PortalPrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalMembersRoute = PortalMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalLatestRoute = PortalLatestRouteImport.update({
  id: "/latest",
  path: "/latest",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalFeaturedRoute = PortalFeaturedRouteImport.update({
  id: "/featured",
  path: "/featured",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalExploreRoute = PortalExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalCookiesRoute = PortalCookiesRouteImport.update({
  id: "/cookies",
  path: "/cookies",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalBrowseRoute = PortalBrowseRouteImport.update({
  id: "/browse",
  path: "/browse",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalAboutRoute = PortalAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalHandleRoute = PortalHandleRouteImport.update({
  id: "/$handle",
  path: "/$handle",
  getParentRoute: () => PortalRouteRoute,
} as any);
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: "/_portal",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const PortalHandleIndexRoute = PortalHandleIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PortalHandleRoute,
} as any);
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const PortalUIdRoute = PortalUIdRouteImport.update({
  id: "/u/$id",
  path: "/u/$id",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalPlaylistTokenRoute = PortalPlaylistTokenRouteImport.update({
  id: "/playlist/$token",
  path: "/playlist/$token",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalPSlugRoute = PortalPSlugRouteImport.update({
  id: "/p/$slug",
  path: "/p/$slug",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalCIdRoute = PortalCIdRouteImport.update({
  id: "/c/$id",
  path: "/c/$id",
  getParentRoute: () => PortalRouteRoute,
} as any);
const PortalHandleSplatRoute = PortalHandleSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => PortalHandleRoute,
} as any);
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsPasswordRoute =
  AuthenticatedSettingsPasswordRouteImport.update({
    id: "/password",
    path: "/password",
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: "/appearance",
    path: "/appearance",
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any);
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedAdminTranscodingRoute =
  AuthenticatedAdminTranscodingRouteImport.update({
    id: "/transcoding",
    path: "/transcoding",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: "/tags",
  path: "/tags",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedAdminStyleGuideRoute =
  AuthenticatedAdminStyleGuideRouteImport.update({
    id: "/style-guide",
    path: "/style-guide",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: "/review",
    path: "/review",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPromotionRoute =
  AuthenticatedAdminPromotionRouteImport.update({
    id: "/promotion",
    path: "/promotion",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPortalRoute =
  AuthenticatedAdminPortalRouteImport.update({
    id: "/portal",
    path: "/portal",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPlaylistsRoute =
  AuthenticatedAdminPlaylistsRouteImport.update({
    id: "/playlists",
    path: "/playlists",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: "/permissions",
    path: "/permissions",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminPaymentRoute =
  AuthenticatedAdminPaymentRouteImport.update({
    id: "/payment",
    path: "/payment",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminLiveRoomsRoute =
  AuthenticatedAdminLiveRoomsRouteImport.update({
    id: "/live-rooms",
    path: "/live-rooms",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminDrmRoute = AuthenticatedAdminDrmRouteImport.update({
  id: "/drm",
  path: "/drm",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedAdminContentStructureRoute =
  AuthenticatedAdminContentStructureRouteImport.update({
    id: "/content-structure",
    path: "/content-structure",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: "/comments",
    path: "/comments",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminChannelsRoute =
  AuthenticatedAdminChannelsRouteImport.update({
    id: "/channels",
    path: "/channels",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: "/categories",
    path: "/categories",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: "/ads",
  path: "/ads",
  getParentRoute: () => AuthenticatedAdminRoute,
} as any);
const AuthenticatedPortalSubscriptionsRoute =
  AuthenticatedPortalSubscriptionsRouteImport.update({
    id: "/subscriptions",
    path: "/subscriptions",
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any);
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any);
const AuthenticatedAdminMediaRouteRoute =
  AuthenticatedAdminMediaRouteRouteImport.update({
    id: "/media",
    path: "/media",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedAdminArticlesRouteRoute =
  AuthenticatedAdminArticlesRouteRouteImport.update({
    id: "/articles",
    path: "/articles",
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any);
const AuthenticatedPortalMeRouteRoute =
  AuthenticatedPortalMeRouteRouteImport.update({
    id: "/me",
    path: "/me",
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any);
const AuthenticatedPortalArticlesRouteRoute =
  AuthenticatedPortalArticlesRouteRouteImport.update({
    id: "/articles",
    path: "/articles",
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any);
const AuthenticatedAdminMediaIndexRoute =
  AuthenticatedAdminMediaIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminMediaRouteRoute,
  } as any);
const AuthenticatedAdminArticlesIndexRoute =
  AuthenticatedAdminArticlesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedAdminArticlesRouteRoute,
  } as any);
const AuthenticatedPortalMeIndexRoute =
  AuthenticatedPortalMeIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalArticlesIndexRoute =
  AuthenticatedPortalArticlesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedPortalArticlesRouteRoute,
  } as any);
const AuthenticatedAdminTranscodingStatusRoute =
  AuthenticatedAdminTranscodingStatusRouteImport.update({
    id: "/status",
    path: "/status",
    getParentRoute: () => AuthenticatedAdminTranscodingRoute,
  } as any);
const AuthenticatedAdminTranscodingProfilesRoute =
  AuthenticatedAdminTranscodingProfilesRouteImport.update({
    id: "/profiles",
    path: "/profiles",
    getParentRoute: () => AuthenticatedAdminTranscodingRoute,
  } as any);
const AuthenticatedAdminMediaIdRoute =
  AuthenticatedAdminMediaIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedAdminMediaRouteRoute,
  } as any);
const AuthenticatedAdminArticlesNewRoute =
  AuthenticatedAdminArticlesNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => AuthenticatedAdminArticlesRouteRoute,
  } as any);
const AuthenticatedPortalMeVideosRoute =
  AuthenticatedPortalMeVideosRouteImport.update({
    id: "/videos",
    path: "/videos",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeUploadRoute =
  AuthenticatedPortalMeUploadRouteImport.update({
    id: "/upload",
    path: "/upload",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeStyleGuideRoute =
  AuthenticatedPortalMeStyleGuideRouteImport.update({
    id: "/style-guide",
    path: "/style-guide",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMePlaylistsRoute =
  AuthenticatedPortalMePlaylistsRouteImport.update({
    id: "/playlists",
    path: "/playlists",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeNotificationsRoute =
  AuthenticatedPortalMeNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeHistoryRoute =
  AuthenticatedPortalMeHistoryRouteImport.update({
    id: "/history",
    path: "/history",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeFavoritesRoute =
  AuthenticatedPortalMeFavoritesRouteImport.update({
    id: "/favorites",
    path: "/favorites",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeChannelsRoute =
  AuthenticatedPortalMeChannelsRouteImport.update({
    id: "/channels",
    path: "/channels",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeChannelRoute =
  AuthenticatedPortalMeChannelRouteImport.update({
    id: "/channel",
    path: "/channel",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalArticlesSlugRoute =
  AuthenticatedPortalArticlesSlugRouteImport.update({
    id: "/$slug",
    path: "/$slug",
    getParentRoute: () => AuthenticatedPortalArticlesRouteRoute,
  } as any);
const AuthenticatedPortalMeArticlesRouteRoute =
  AuthenticatedPortalMeArticlesRouteRouteImport.update({
    id: "/articles",
    path: "/articles",
    getParentRoute: () => AuthenticatedPortalMeRouteRoute,
  } as any);
const AuthenticatedPortalMeArticlesIndexRoute =
  AuthenticatedPortalMeArticlesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedPortalMeArticlesRouteRoute,
  } as any);
const AuthenticatedAdminArticlesIdEditRoute =
  AuthenticatedAdminArticlesIdEditRouteImport.update({
    id: "/$id/edit",
    path: "/$id/edit",
    getParentRoute: () => AuthenticatedAdminArticlesRouteRoute,
  } as any);
const AuthenticatedPortalMediaShortTokenEditRoute =
  AuthenticatedPortalMediaShortTokenEditRouteImport.update({
    id: "/media/$shortToken/edit",
    path: "/media/$shortToken/edit",
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any);
const AuthenticatedPortalMeArticlesNewRoute =
  AuthenticatedPortalMeArticlesNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => AuthenticatedPortalMeArticlesRouteRoute,
  } as any);
const AuthenticatedPortalMeArticlesTokenEditRoute =
  AuthenticatedPortalMeArticlesTokenEditRouteImport.update({
    id: "/$token/edit",
    path: "/$token/edit",
    getParentRoute: () => AuthenticatedPortalMeArticlesRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof PortalIndexRoute;
  "/admin": typeof AuthenticatedAdminRouteWithChildren;
  "/settings": typeof AuthenticatedSettingsRouteWithChildren;
  "/$handle": typeof PortalHandleRouteWithChildren;
  "/about": typeof PortalAboutRoute;
  "/browse": typeof PortalBrowseRoute;
  "/cookies": typeof PortalCookiesRoute;
  "/explore": typeof PortalExploreRoute;
  "/featured": typeof PortalFeaturedRoute;
  "/latest": typeof PortalLatestRoute;
  "/members": typeof PortalMembersRoute;
  "/privacy": typeof PortalPrivacyRoute;
  "/search": typeof PortalSearchRoute;
  "/tags": typeof PortalTagsRoute;
  "/terms": typeof PortalTermsRoute;
  "/trending": typeof PortalTrendingRoute;
  "/watch": typeof PortalWatchRoute;
  "/auth/signin": typeof AuthSigninRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/articles": typeof AuthenticatedPortalArticlesRouteRouteWithChildren;
  "/me": typeof AuthenticatedPortalMeRouteRouteWithChildren;
  "/admin/articles": typeof AuthenticatedAdminArticlesRouteRouteWithChildren;
  "/admin/media": typeof AuthenticatedAdminMediaRouteRouteWithChildren;
  "/notifications": typeof AuthenticatedPortalNotificationsRoute;
  "/subscriptions": typeof AuthenticatedPortalSubscriptionsRoute;
  "/admin/ads": typeof AuthenticatedAdminAdsRoute;
  "/admin/categories": typeof AuthenticatedAdminCategoriesRoute;
  "/admin/channels": typeof AuthenticatedAdminChannelsRoute;
  "/admin/comments": typeof AuthenticatedAdminCommentsRoute;
  "/admin/content-structure": typeof AuthenticatedAdminContentStructureRoute;
  "/admin/drm": typeof AuthenticatedAdminDrmRoute;
  "/admin/live-rooms": typeof AuthenticatedAdminLiveRoomsRoute;
  "/admin/notifications": typeof AuthenticatedAdminNotificationsRoute;
  "/admin/payment": typeof AuthenticatedAdminPaymentRoute;
  "/admin/permissions": typeof AuthenticatedAdminPermissionsRoute;
  "/admin/playlists": typeof AuthenticatedAdminPlaylistsRoute;
  "/admin/portal": typeof AuthenticatedAdminPortalRoute;
  "/admin/promotion": typeof AuthenticatedAdminPromotionRoute;
  "/admin/review": typeof AuthenticatedAdminReviewRoute;
  "/admin/settings": typeof AuthenticatedAdminSettingsRoute;
  "/admin/style-guide": typeof AuthenticatedAdminStyleGuideRoute;
  "/admin/tags": typeof AuthenticatedAdminTagsRoute;
  "/admin/transcoding": typeof AuthenticatedAdminTranscodingRouteWithChildren;
  "/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/settings/appearance": typeof AuthenticatedSettingsAppearanceRoute;
  "/settings/password": typeof AuthenticatedSettingsPasswordRoute;
  "/settings/preferences": typeof AuthenticatedSettingsPreferencesRoute;
  "/settings/profile": typeof AuthenticatedSettingsProfileRoute;
  "/$handle/$": typeof PortalHandleSplatRoute;
  "/c/$id": typeof PortalCIdRoute;
  "/p/$slug": typeof PortalPSlugRoute;
  "/playlist/$token": typeof PortalPlaylistTokenRoute;
  "/u/$id": typeof PortalUIdRoute;
  "/admin/": typeof AuthenticatedAdminIndexRoute;
  "/$handle/": typeof PortalHandleIndexRoute;
  "/me/articles": typeof AuthenticatedPortalMeArticlesRouteRouteWithChildren;
  "/articles/$slug": typeof AuthenticatedPortalArticlesSlugRoute;
  "/me/channel": typeof AuthenticatedPortalMeChannelRoute;
  "/me/channels": typeof AuthenticatedPortalMeChannelsRoute;
  "/me/favorites": typeof AuthenticatedPortalMeFavoritesRoute;
  "/me/history": typeof AuthenticatedPortalMeHistoryRoute;
  "/me/notifications": typeof AuthenticatedPortalMeNotificationsRoute;
  "/me/playlists": typeof AuthenticatedPortalMePlaylistsRoute;
  "/me/style-guide": typeof AuthenticatedPortalMeStyleGuideRoute;
  "/me/upload": typeof AuthenticatedPortalMeUploadRoute;
  "/me/videos": typeof AuthenticatedPortalMeVideosRoute;
  "/admin/articles/new": typeof AuthenticatedAdminArticlesNewRoute;
  "/admin/media/$id": typeof AuthenticatedAdminMediaIdRoute;
  "/admin/transcoding/profiles": typeof AuthenticatedAdminTranscodingProfilesRoute;
  "/admin/transcoding/status": typeof AuthenticatedAdminTranscodingStatusRoute;
  "/articles/": typeof AuthenticatedPortalArticlesIndexRoute;
  "/me/": typeof AuthenticatedPortalMeIndexRoute;
  "/admin/articles/": typeof AuthenticatedAdminArticlesIndexRoute;
  "/admin/media/": typeof AuthenticatedAdminMediaIndexRoute;
  "/me/articles/new": typeof AuthenticatedPortalMeArticlesNewRoute;
  "/media/$shortToken/edit": typeof AuthenticatedPortalMediaShortTokenEditRoute;
  "/admin/articles/$id/edit": typeof AuthenticatedAdminArticlesIdEditRoute;
  "/me/articles/": typeof AuthenticatedPortalMeArticlesIndexRoute;
  "/me/articles/$token/edit": typeof AuthenticatedPortalMeArticlesTokenEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof PortalIndexRoute;
  "/settings": typeof AuthenticatedSettingsRouteWithChildren;
  "/about": typeof PortalAboutRoute;
  "/browse": typeof PortalBrowseRoute;
  "/cookies": typeof PortalCookiesRoute;
  "/explore": typeof PortalExploreRoute;
  "/featured": typeof PortalFeaturedRoute;
  "/latest": typeof PortalLatestRoute;
  "/members": typeof PortalMembersRoute;
  "/privacy": typeof PortalPrivacyRoute;
  "/search": typeof PortalSearchRoute;
  "/tags": typeof PortalTagsRoute;
  "/terms": typeof PortalTermsRoute;
  "/trending": typeof PortalTrendingRoute;
  "/watch": typeof PortalWatchRoute;
  "/auth/signin": typeof AuthSigninRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/notifications": typeof AuthenticatedPortalNotificationsRoute;
  "/subscriptions": typeof AuthenticatedPortalSubscriptionsRoute;
  "/admin/ads": typeof AuthenticatedAdminAdsRoute;
  "/admin/categories": typeof AuthenticatedAdminCategoriesRoute;
  "/admin/channels": typeof AuthenticatedAdminChannelsRoute;
  "/admin/comments": typeof AuthenticatedAdminCommentsRoute;
  "/admin/content-structure": typeof AuthenticatedAdminContentStructureRoute;
  "/admin/drm": typeof AuthenticatedAdminDrmRoute;
  "/admin/live-rooms": typeof AuthenticatedAdminLiveRoomsRoute;
  "/admin/notifications": typeof AuthenticatedAdminNotificationsRoute;
  "/admin/payment": typeof AuthenticatedAdminPaymentRoute;
  "/admin/permissions": typeof AuthenticatedAdminPermissionsRoute;
  "/admin/playlists": typeof AuthenticatedAdminPlaylistsRoute;
  "/admin/portal": typeof AuthenticatedAdminPortalRoute;
  "/admin/promotion": typeof AuthenticatedAdminPromotionRoute;
  "/admin/review": typeof AuthenticatedAdminReviewRoute;
  "/admin/settings": typeof AuthenticatedAdminSettingsRoute;
  "/admin/style-guide": typeof AuthenticatedAdminStyleGuideRoute;
  "/admin/tags": typeof AuthenticatedAdminTagsRoute;
  "/admin/transcoding": typeof AuthenticatedAdminTranscodingRouteWithChildren;
  "/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/settings/appearance": typeof AuthenticatedSettingsAppearanceRoute;
  "/settings/password": typeof AuthenticatedSettingsPasswordRoute;
  "/settings/preferences": typeof AuthenticatedSettingsPreferencesRoute;
  "/settings/profile": typeof AuthenticatedSettingsProfileRoute;
  "/$handle/$": typeof PortalHandleSplatRoute;
  "/c/$id": typeof PortalCIdRoute;
  "/p/$slug": typeof PortalPSlugRoute;
  "/playlist/$token": typeof PortalPlaylistTokenRoute;
  "/u/$id": typeof PortalUIdRoute;
  "/admin": typeof AuthenticatedAdminIndexRoute;
  "/$handle": typeof PortalHandleIndexRoute;
  "/articles/$slug": typeof AuthenticatedPortalArticlesSlugRoute;
  "/me/channel": typeof AuthenticatedPortalMeChannelRoute;
  "/me/channels": typeof AuthenticatedPortalMeChannelsRoute;
  "/me/favorites": typeof AuthenticatedPortalMeFavoritesRoute;
  "/me/history": typeof AuthenticatedPortalMeHistoryRoute;
  "/me/notifications": typeof AuthenticatedPortalMeNotificationsRoute;
  "/me/playlists": typeof AuthenticatedPortalMePlaylistsRoute;
  "/me/style-guide": typeof AuthenticatedPortalMeStyleGuideRoute;
  "/me/upload": typeof AuthenticatedPortalMeUploadRoute;
  "/me/videos": typeof AuthenticatedPortalMeVideosRoute;
  "/admin/articles/new": typeof AuthenticatedAdminArticlesNewRoute;
  "/admin/media/$id": typeof AuthenticatedAdminMediaIdRoute;
  "/admin/transcoding/profiles": typeof AuthenticatedAdminTranscodingProfilesRoute;
  "/admin/transcoding/status": typeof AuthenticatedAdminTranscodingStatusRoute;
  "/articles": typeof AuthenticatedPortalArticlesIndexRoute;
  "/me": typeof AuthenticatedPortalMeIndexRoute;
  "/admin/articles": typeof AuthenticatedAdminArticlesIndexRoute;
  "/admin/media": typeof AuthenticatedAdminMediaIndexRoute;
  "/me/articles/new": typeof AuthenticatedPortalMeArticlesNewRoute;
  "/media/$shortToken/edit": typeof AuthenticatedPortalMediaShortTokenEditRoute;
  "/admin/articles/$id/edit": typeof AuthenticatedAdminArticlesIdEditRoute;
  "/me/articles": typeof AuthenticatedPortalMeArticlesIndexRoute;
  "/me/articles/$token/edit": typeof AuthenticatedPortalMeArticlesTokenEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_portal": typeof PortalRouteRouteWithChildren;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_authenticated/_portal": typeof AuthenticatedPortalRouteWithChildren;
  "/_authenticated/admin": typeof AuthenticatedAdminRouteWithChildren;
  "/_authenticated/settings": typeof AuthenticatedSettingsRouteWithChildren;
  "/_portal/$handle": typeof PortalHandleRouteWithChildren;
  "/_portal/about": typeof PortalAboutRoute;
  "/_portal/browse": typeof PortalBrowseRoute;
  "/_portal/cookies": typeof PortalCookiesRoute;
  "/_portal/explore": typeof PortalExploreRoute;
  "/_portal/featured": typeof PortalFeaturedRoute;
  "/_portal/latest": typeof PortalLatestRoute;
  "/_portal/members": typeof PortalMembersRoute;
  "/_portal/privacy": typeof PortalPrivacyRoute;
  "/_portal/search": typeof PortalSearchRoute;
  "/_portal/tags": typeof PortalTagsRoute;
  "/_portal/terms": typeof PortalTermsRoute;
  "/_portal/trending": typeof PortalTrendingRoute;
  "/_portal/watch": typeof PortalWatchRoute;
  "/auth/signin": typeof AuthSigninRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/_portal/": typeof PortalIndexRoute;
  "/_authenticated/_portal/articles": typeof AuthenticatedPortalArticlesRouteRouteWithChildren;
  "/_authenticated/_portal/me": typeof AuthenticatedPortalMeRouteRouteWithChildren;
  "/_authenticated/admin/articles": typeof AuthenticatedAdminArticlesRouteRouteWithChildren;
  "/_authenticated/admin/media": typeof AuthenticatedAdminMediaRouteRouteWithChildren;
  "/_authenticated/_portal/notifications": typeof AuthenticatedPortalNotificationsRoute;
  "/_authenticated/_portal/subscriptions": typeof AuthenticatedPortalSubscriptionsRoute;
  "/_authenticated/admin/ads": typeof AuthenticatedAdminAdsRoute;
  "/_authenticated/admin/categories": typeof AuthenticatedAdminCategoriesRoute;
  "/_authenticated/admin/channels": typeof AuthenticatedAdminChannelsRoute;
  "/_authenticated/admin/comments": typeof AuthenticatedAdminCommentsRoute;
  "/_authenticated/admin/content-structure": typeof AuthenticatedAdminContentStructureRoute;
  "/_authenticated/admin/drm": typeof AuthenticatedAdminDrmRoute;
  "/_authenticated/admin/live-rooms": typeof AuthenticatedAdminLiveRoomsRoute;
  "/_authenticated/admin/notifications": typeof AuthenticatedAdminNotificationsRoute;
  "/_authenticated/admin/payment": typeof AuthenticatedAdminPaymentRoute;
  "/_authenticated/admin/permissions": typeof AuthenticatedAdminPermissionsRoute;
  "/_authenticated/admin/playlists": typeof AuthenticatedAdminPlaylistsRoute;
  "/_authenticated/admin/portal": typeof AuthenticatedAdminPortalRoute;
  "/_authenticated/admin/promotion": typeof AuthenticatedAdminPromotionRoute;
  "/_authenticated/admin/review": typeof AuthenticatedAdminReviewRoute;
  "/_authenticated/admin/settings": typeof AuthenticatedAdminSettingsRoute;
  "/_authenticated/admin/style-guide": typeof AuthenticatedAdminStyleGuideRoute;
  "/_authenticated/admin/tags": typeof AuthenticatedAdminTagsRoute;
  "/_authenticated/admin/transcoding": typeof AuthenticatedAdminTranscodingRouteWithChildren;
  "/_authenticated/admin/users": typeof AuthenticatedAdminUsersRoute;
  "/_authenticated/settings/appearance": typeof AuthenticatedSettingsAppearanceRoute;
  "/_authenticated/settings/password": typeof AuthenticatedSettingsPasswordRoute;
  "/_authenticated/settings/preferences": typeof AuthenticatedSettingsPreferencesRoute;
  "/_authenticated/settings/profile": typeof AuthenticatedSettingsProfileRoute;
  "/_portal/$handle/$": typeof PortalHandleSplatRoute;
  "/_portal/c/$id": typeof PortalCIdRoute;
  "/_portal/p/$slug": typeof PortalPSlugRoute;
  "/_portal/playlist/$token": typeof PortalPlaylistTokenRoute;
  "/_portal/u/$id": typeof PortalUIdRoute;
  "/_authenticated/admin/": typeof AuthenticatedAdminIndexRoute;
  "/_portal/$handle/": typeof PortalHandleIndexRoute;
  "/_authenticated/_portal/me/articles": typeof AuthenticatedPortalMeArticlesRouteRouteWithChildren;
  "/_authenticated/_portal/articles/$slug": typeof AuthenticatedPortalArticlesSlugRoute;
  "/_authenticated/_portal/me/channel": typeof AuthenticatedPortalMeChannelRoute;
  "/_authenticated/_portal/me/channels": typeof AuthenticatedPortalMeChannelsRoute;
  "/_authenticated/_portal/me/favorites": typeof AuthenticatedPortalMeFavoritesRoute;
  "/_authenticated/_portal/me/history": typeof AuthenticatedPortalMeHistoryRoute;
  "/_authenticated/_portal/me/notifications": typeof AuthenticatedPortalMeNotificationsRoute;
  "/_authenticated/_portal/me/playlists": typeof AuthenticatedPortalMePlaylistsRoute;
  "/_authenticated/_portal/me/style-guide": typeof AuthenticatedPortalMeStyleGuideRoute;
  "/_authenticated/_portal/me/upload": typeof AuthenticatedPortalMeUploadRoute;
  "/_authenticated/_portal/me/videos": typeof AuthenticatedPortalMeVideosRoute;
  "/_authenticated/admin/articles/new": typeof AuthenticatedAdminArticlesNewRoute;
  "/_authenticated/admin/media/$id": typeof AuthenticatedAdminMediaIdRoute;
  "/_authenticated/admin/transcoding/profiles": typeof AuthenticatedAdminTranscodingProfilesRoute;
  "/_authenticated/admin/transcoding/status": typeof AuthenticatedAdminTranscodingStatusRoute;
  "/_authenticated/_portal/articles/": typeof AuthenticatedPortalArticlesIndexRoute;
  "/_authenticated/_portal/me/": typeof AuthenticatedPortalMeIndexRoute;
  "/_authenticated/admin/articles/": typeof AuthenticatedAdminArticlesIndexRoute;
  "/_authenticated/admin/media/": typeof AuthenticatedAdminMediaIndexRoute;
  "/_authenticated/_portal/me/articles/new": typeof AuthenticatedPortalMeArticlesNewRoute;
  "/_authenticated/_portal/media/$shortToken/edit": typeof AuthenticatedPortalMediaShortTokenEditRoute;
  "/_authenticated/admin/articles/$id/edit": typeof AuthenticatedAdminArticlesIdEditRoute;
  "/_authenticated/_portal/me/articles/": typeof AuthenticatedPortalMeArticlesIndexRoute;
  "/_authenticated/_portal/me/articles/$token/edit": typeof AuthenticatedPortalMeArticlesTokenEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/settings"
    | "/$handle"
    | "/about"
    | "/browse"
    | "/cookies"
    | "/explore"
    | "/featured"
    | "/latest"
    | "/members"
    | "/privacy"
    | "/search"
    | "/tags"
    | "/terms"
    | "/trending"
    | "/watch"
    | "/auth/signin"
    | "/auth/signup"
    | "/articles"
    | "/me"
    | "/admin/articles"
    | "/admin/media"
    | "/notifications"
    | "/subscriptions"
    | "/admin/ads"
    | "/admin/categories"
    | "/admin/channels"
    | "/admin/comments"
    | "/admin/content-structure"
    | "/admin/drm"
    | "/admin/live-rooms"
    | "/admin/notifications"
    | "/admin/payment"
    | "/admin/permissions"
    | "/admin/playlists"
    | "/admin/portal"
    | "/admin/promotion"
    | "/admin/review"
    | "/admin/settings"
    | "/admin/style-guide"
    | "/admin/tags"
    | "/admin/transcoding"
    | "/admin/users"
    | "/settings/appearance"
    | "/settings/password"
    | "/settings/preferences"
    | "/settings/profile"
    | "/$handle/$"
    | "/c/$id"
    | "/p/$slug"
    | "/playlist/$token"
    | "/u/$id"
    | "/admin/"
    | "/$handle/"
    | "/me/articles"
    | "/articles/$slug"
    | "/me/channel"
    | "/me/channels"
    | "/me/favorites"
    | "/me/history"
    | "/me/notifications"
    | "/me/playlists"
    | "/me/style-guide"
    | "/me/upload"
    | "/me/videos"
    | "/admin/articles/new"
    | "/admin/media/$id"
    | "/admin/transcoding/profiles"
    | "/admin/transcoding/status"
    | "/articles/"
    | "/me/"
    | "/admin/articles/"
    | "/admin/media/"
    | "/me/articles/new"
    | "/media/$shortToken/edit"
    | "/admin/articles/$id/edit"
    | "/me/articles/"
    | "/me/articles/$token/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/about"
    | "/browse"
    | "/cookies"
    | "/explore"
    | "/featured"
    | "/latest"
    | "/members"
    | "/privacy"
    | "/search"
    | "/tags"
    | "/terms"
    | "/trending"
    | "/watch"
    | "/auth/signin"
    | "/auth/signup"
    | "/notifications"
    | "/subscriptions"
    | "/admin/ads"
    | "/admin/categories"
    | "/admin/channels"
    | "/admin/comments"
    | "/admin/content-structure"
    | "/admin/drm"
    | "/admin/live-rooms"
    | "/admin/notifications"
    | "/admin/payment"
    | "/admin/permissions"
    | "/admin/playlists"
    | "/admin/portal"
    | "/admin/promotion"
    | "/admin/review"
    | "/admin/settings"
    | "/admin/style-guide"
    | "/admin/tags"
    | "/admin/transcoding"
    | "/admin/users"
    | "/settings/appearance"
    | "/settings/password"
    | "/settings/preferences"
    | "/settings/profile"
    | "/$handle/$"
    | "/c/$id"
    | "/p/$slug"
    | "/playlist/$token"
    | "/u/$id"
    | "/admin"
    | "/$handle"
    | "/articles/$slug"
    | "/me/channel"
    | "/me/channels"
    | "/me/favorites"
    | "/me/history"
    | "/me/notifications"
    | "/me/playlists"
    | "/me/style-guide"
    | "/me/upload"
    | "/me/videos"
    | "/admin/articles/new"
    | "/admin/media/$id"
    | "/admin/transcoding/profiles"
    | "/admin/transcoding/status"
    | "/articles"
    | "/me"
    | "/admin/articles"
    | "/admin/media"
    | "/me/articles/new"
    | "/media/$shortToken/edit"
    | "/admin/articles/$id/edit"
    | "/me/articles"
    | "/me/articles/$token/edit";
  id:
    | "__root__"
    | "/_portal"
    | "/_authenticated"
    | "/_authenticated/_portal"
    | "/_authenticated/admin"
    | "/_authenticated/settings"
    | "/_portal/$handle"
    | "/_portal/about"
    | "/_portal/browse"
    | "/_portal/cookies"
    | "/_portal/explore"
    | "/_portal/featured"
    | "/_portal/latest"
    | "/_portal/members"
    | "/_portal/privacy"
    | "/_portal/search"
    | "/_portal/tags"
    | "/_portal/terms"
    | "/_portal/trending"
    | "/_portal/watch"
    | "/auth/signin"
    | "/auth/signup"
    | "/_portal/"
    | "/_authenticated/_portal/articles"
    | "/_authenticated/_portal/me"
    | "/_authenticated/admin/articles"
    | "/_authenticated/admin/media"
    | "/_authenticated/_portal/notifications"
    | "/_authenticated/_portal/subscriptions"
    | "/_authenticated/admin/ads"
    | "/_authenticated/admin/categories"
    | "/_authenticated/admin/channels"
    | "/_authenticated/admin/comments"
    | "/_authenticated/admin/content-structure"
    | "/_authenticated/admin/drm"
    | "/_authenticated/admin/live-rooms"
    | "/_authenticated/admin/notifications"
    | "/_authenticated/admin/payment"
    | "/_authenticated/admin/permissions"
    | "/_authenticated/admin/playlists"
    | "/_authenticated/admin/portal"
    | "/_authenticated/admin/promotion"
    | "/_authenticated/admin/review"
    | "/_authenticated/admin/settings"
    | "/_authenticated/admin/style-guide"
    | "/_authenticated/admin/tags"
    | "/_authenticated/admin/transcoding"
    | "/_authenticated/admin/users"
    | "/_authenticated/settings/appearance"
    | "/_authenticated/settings/password"
    | "/_authenticated/settings/preferences"
    | "/_authenticated/settings/profile"
    | "/_portal/$handle/$"
    | "/_portal/c/$id"
    | "/_portal/p/$slug"
    | "/_portal/playlist/$token"
    | "/_portal/u/$id"
    | "/_authenticated/admin/"
    | "/_portal/$handle/"
    | "/_authenticated/_portal/me/articles"
    | "/_authenticated/_portal/articles/$slug"
    | "/_authenticated/_portal/me/channel"
    | "/_authenticated/_portal/me/channels"
    | "/_authenticated/_portal/me/favorites"
    | "/_authenticated/_portal/me/history"
    | "/_authenticated/_portal/me/notifications"
    | "/_authenticated/_portal/me/playlists"
    | "/_authenticated/_portal/me/style-guide"
    | "/_authenticated/_portal/me/upload"
    | "/_authenticated/_portal/me/videos"
    | "/_authenticated/admin/articles/new"
    | "/_authenticated/admin/media/$id"
    | "/_authenticated/admin/transcoding/profiles"
    | "/_authenticated/admin/transcoding/status"
    | "/_authenticated/_portal/articles/"
    | "/_authenticated/_portal/me/"
    | "/_authenticated/admin/articles/"
    | "/_authenticated/admin/media/"
    | "/_authenticated/_portal/me/articles/new"
    | "/_authenticated/_portal/media/$shortToken/edit"
    | "/_authenticated/admin/articles/$id/edit"
    | "/_authenticated/_portal/me/articles/"
    | "/_authenticated/_portal/me/articles/$token/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PortalRouteRoute: typeof PortalRouteRouteWithChildren;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_portal": {
      id: "/_portal";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof PortalRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_portal/": {
      id: "/_portal/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof PortalIndexRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/auth/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/signin": {
      id: "/auth/signin";
      path: "/auth/signin";
      fullPath: "/auth/signin";
      preLoaderRoute: typeof AuthSigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_portal/watch": {
      id: "/_portal/watch";
      path: "/watch";
      fullPath: "/watch";
      preLoaderRoute: typeof PortalWatchRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/trending": {
      id: "/_portal/trending";
      path: "/trending";
      fullPath: "/trending";
      preLoaderRoute: typeof PortalTrendingRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/terms": {
      id: "/_portal/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof PortalTermsRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/tags": {
      id: "/_portal/tags";
      path: "/tags";
      fullPath: "/tags";
      preLoaderRoute: typeof PortalTagsRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/search": {
      id: "/_portal/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof PortalSearchRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/privacy": {
      id: "/_portal/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PortalPrivacyRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/members": {
      id: "/_portal/members";
      path: "/members";
      fullPath: "/members";
      preLoaderRoute: typeof PortalMembersRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/latest": {
      id: "/_portal/latest";
      path: "/latest";
      fullPath: "/latest";
      preLoaderRoute: typeof PortalLatestRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/featured": {
      id: "/_portal/featured";
      path: "/featured";
      fullPath: "/featured";
      preLoaderRoute: typeof PortalFeaturedRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/explore": {
      id: "/_portal/explore";
      path: "/explore";
      fullPath: "/explore";
      preLoaderRoute: typeof PortalExploreRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/cookies": {
      id: "/_portal/cookies";
      path: "/cookies";
      fullPath: "/cookies";
      preLoaderRoute: typeof PortalCookiesRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/browse": {
      id: "/_portal/browse";
      path: "/browse";
      fullPath: "/browse";
      preLoaderRoute: typeof PortalBrowseRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/about": {
      id: "/_portal/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof PortalAboutRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/$handle": {
      id: "/_portal/$handle";
      path: "/$handle";
      fullPath: "/$handle";
      preLoaderRoute: typeof PortalHandleRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_authenticated/settings": {
      id: "/_authenticated/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/admin": {
      id: "/_authenticated/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AuthenticatedAdminRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_portal": {
      id: "/_authenticated/_portal";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedPortalRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_portal/$handle/": {
      id: "/_portal/$handle/";
      path: "/";
      fullPath: "/$handle/";
      preLoaderRoute: typeof PortalHandleIndexRouteImport;
      parentRoute: typeof PortalHandleRoute;
    };
    "/_authenticated/admin/": {
      id: "/_authenticated/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_portal/u/$id": {
      id: "/_portal/u/$id";
      path: "/u/$id";
      fullPath: "/u/$id";
      preLoaderRoute: typeof PortalUIdRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/playlist/$token": {
      id: "/_portal/playlist/$token";
      path: "/playlist/$token";
      fullPath: "/playlist/$token";
      preLoaderRoute: typeof PortalPlaylistTokenRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/p/$slug": {
      id: "/_portal/p/$slug";
      path: "/p/$slug";
      fullPath: "/p/$slug";
      preLoaderRoute: typeof PortalPSlugRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/c/$id": {
      id: "/_portal/c/$id";
      path: "/c/$id";
      fullPath: "/c/$id";
      preLoaderRoute: typeof PortalCIdRouteImport;
      parentRoute: typeof PortalRouteRoute;
    };
    "/_portal/$handle/$": {
      id: "/_portal/$handle/$";
      path: "/$";
      fullPath: "/$handle/$";
      preLoaderRoute: typeof PortalHandleSplatRouteImport;
      parentRoute: typeof PortalHandleRoute;
    };
    "/_authenticated/settings/profile": {
      id: "/_authenticated/settings/profile";
      path: "/profile";
      fullPath: "/settings/profile";
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    "/_authenticated/settings/preferences": {
      id: "/_authenticated/settings/preferences";
      path: "/preferences";
      fullPath: "/settings/preferences";
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    "/_authenticated/settings/password": {
      id: "/_authenticated/settings/password";
      path: "/password";
      fullPath: "/settings/password";
      preLoaderRoute: typeof AuthenticatedSettingsPasswordRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    "/_authenticated/settings/appearance": {
      id: "/_authenticated/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport;
      parentRoute: typeof AuthenticatedSettingsRoute;
    };
    "/_authenticated/admin/users": {
      id: "/_authenticated/admin/users";
      path: "/users";
      fullPath: "/admin/users";
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/transcoding": {
      id: "/_authenticated/admin/transcoding";
      path: "/transcoding";
      fullPath: "/admin/transcoding";
      preLoaderRoute: typeof AuthenticatedAdminTranscodingRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/tags": {
      id: "/_authenticated/admin/tags";
      path: "/tags";
      fullPath: "/admin/tags";
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/style-guide": {
      id: "/_authenticated/admin/style-guide";
      path: "/style-guide";
      fullPath: "/admin/style-guide";
      preLoaderRoute: typeof AuthenticatedAdminStyleGuideRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/settings": {
      id: "/_authenticated/admin/settings";
      path: "/settings";
      fullPath: "/admin/settings";
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/review": {
      id: "/_authenticated/admin/review";
      path: "/review";
      fullPath: "/admin/review";
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/promotion": {
      id: "/_authenticated/admin/promotion";
      path: "/promotion";
      fullPath: "/admin/promotion";
      preLoaderRoute: typeof AuthenticatedAdminPromotionRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/portal": {
      id: "/_authenticated/admin/portal";
      path: "/portal";
      fullPath: "/admin/portal";
      preLoaderRoute: typeof AuthenticatedAdminPortalRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/playlists": {
      id: "/_authenticated/admin/playlists";
      path: "/playlists";
      fullPath: "/admin/playlists";
      preLoaderRoute: typeof AuthenticatedAdminPlaylistsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/permissions": {
      id: "/_authenticated/admin/permissions";
      path: "/permissions";
      fullPath: "/admin/permissions";
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/payment": {
      id: "/_authenticated/admin/payment";
      path: "/payment";
      fullPath: "/admin/payment";
      preLoaderRoute: typeof AuthenticatedAdminPaymentRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/notifications": {
      id: "/_authenticated/admin/notifications";
      path: "/notifications";
      fullPath: "/admin/notifications";
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/live-rooms": {
      id: "/_authenticated/admin/live-rooms";
      path: "/live-rooms";
      fullPath: "/admin/live-rooms";
      preLoaderRoute: typeof AuthenticatedAdminLiveRoomsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/drm": {
      id: "/_authenticated/admin/drm";
      path: "/drm";
      fullPath: "/admin/drm";
      preLoaderRoute: typeof AuthenticatedAdminDrmRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/content-structure": {
      id: "/_authenticated/admin/content-structure";
      path: "/content-structure";
      fullPath: "/admin/content-structure";
      preLoaderRoute: typeof AuthenticatedAdminContentStructureRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/comments": {
      id: "/_authenticated/admin/comments";
      path: "/comments";
      fullPath: "/admin/comments";
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/channels": {
      id: "/_authenticated/admin/channels";
      path: "/channels";
      fullPath: "/admin/channels";
      preLoaderRoute: typeof AuthenticatedAdminChannelsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/categories": {
      id: "/_authenticated/admin/categories";
      path: "/categories";
      fullPath: "/admin/categories";
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/ads": {
      id: "/_authenticated/admin/ads";
      path: "/ads";
      fullPath: "/admin/ads";
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/_portal/subscriptions": {
      id: "/_authenticated/_portal/subscriptions";
      path: "/subscriptions";
      fullPath: "/subscriptions";
      preLoaderRoute: typeof AuthenticatedPortalSubscriptionsRouteImport;
      parentRoute: typeof AuthenticatedPortalRoute;
    };
    "/_authenticated/_portal/notifications": {
      id: "/_authenticated/_portal/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport;
      parentRoute: typeof AuthenticatedPortalRoute;
    };
    "/_authenticated/admin/media": {
      id: "/_authenticated/admin/media";
      path: "/media";
      fullPath: "/admin/media";
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/admin/articles": {
      id: "/_authenticated/admin/articles";
      path: "/articles";
      fullPath: "/admin/articles";
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteRouteImport;
      parentRoute: typeof AuthenticatedAdminRoute;
    };
    "/_authenticated/_portal/me": {
      id: "/_authenticated/_portal/me";
      path: "/me";
      fullPath: "/me";
      preLoaderRoute: typeof AuthenticatedPortalMeRouteRouteImport;
      parentRoute: typeof AuthenticatedPortalRoute;
    };
    "/_authenticated/_portal/articles": {
      id: "/_authenticated/_portal/articles";
      path: "/articles";
      fullPath: "/articles";
      preLoaderRoute: typeof AuthenticatedPortalArticlesRouteRouteImport;
      parentRoute: typeof AuthenticatedPortalRoute;
    };
    "/_authenticated/admin/media/": {
      id: "/_authenticated/admin/media/";
      path: "/";
      fullPath: "/admin/media/";
      preLoaderRoute: typeof AuthenticatedAdminMediaIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminMediaRouteRoute;
    };
    "/_authenticated/admin/articles/": {
      id: "/_authenticated/admin/articles/";
      path: "/";
      fullPath: "/admin/articles/";
      preLoaderRoute: typeof AuthenticatedAdminArticlesIndexRouteImport;
      parentRoute: typeof AuthenticatedAdminArticlesRouteRoute;
    };
    "/_authenticated/_portal/me/": {
      id: "/_authenticated/_portal/me/";
      path: "/";
      fullPath: "/me/";
      preLoaderRoute: typeof AuthenticatedPortalMeIndexRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/articles/": {
      id: "/_authenticated/_portal/articles/";
      path: "/";
      fullPath: "/articles/";
      preLoaderRoute: typeof AuthenticatedPortalArticlesIndexRouteImport;
      parentRoute: typeof AuthenticatedPortalArticlesRouteRoute;
    };
    "/_authenticated/admin/transcoding/status": {
      id: "/_authenticated/admin/transcoding/status";
      path: "/status";
      fullPath: "/admin/transcoding/status";
      preLoaderRoute: typeof AuthenticatedAdminTranscodingStatusRouteImport;
      parentRoute: typeof AuthenticatedAdminTranscodingRoute;
    };
    "/_authenticated/admin/transcoding/profiles": {
      id: "/_authenticated/admin/transcoding/profiles";
      path: "/profiles";
      fullPath: "/admin/transcoding/profiles";
      preLoaderRoute: typeof AuthenticatedAdminTranscodingProfilesRouteImport;
      parentRoute: typeof AuthenticatedAdminTranscodingRoute;
    };
    "/_authenticated/admin/media/$id": {
      id: "/_authenticated/admin/media/$id";
      path: "/$id";
      fullPath: "/admin/media/$id";
      preLoaderRoute: typeof AuthenticatedAdminMediaIdRouteImport;
      parentRoute: typeof AuthenticatedAdminMediaRouteRoute;
    };
    "/_authenticated/admin/articles/new": {
      id: "/_authenticated/admin/articles/new";
      path: "/new";
      fullPath: "/admin/articles/new";
      preLoaderRoute: typeof AuthenticatedAdminArticlesNewRouteImport;
      parentRoute: typeof AuthenticatedAdminArticlesRouteRoute;
    };
    "/_authenticated/_portal/me/videos": {
      id: "/_authenticated/_portal/me/videos";
      path: "/videos";
      fullPath: "/me/videos";
      preLoaderRoute: typeof AuthenticatedPortalMeVideosRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/upload": {
      id: "/_authenticated/_portal/me/upload";
      path: "/upload";
      fullPath: "/me/upload";
      preLoaderRoute: typeof AuthenticatedPortalMeUploadRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/style-guide": {
      id: "/_authenticated/_portal/me/style-guide";
      path: "/style-guide";
      fullPath: "/me/style-guide";
      preLoaderRoute: typeof AuthenticatedPortalMeStyleGuideRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/playlists": {
      id: "/_authenticated/_portal/me/playlists";
      path: "/playlists";
      fullPath: "/me/playlists";
      preLoaderRoute: typeof AuthenticatedPortalMePlaylistsRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/notifications": {
      id: "/_authenticated/_portal/me/notifications";
      path: "/notifications";
      fullPath: "/me/notifications";
      preLoaderRoute: typeof AuthenticatedPortalMeNotificationsRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/history": {
      id: "/_authenticated/_portal/me/history";
      path: "/history";
      fullPath: "/me/history";
      preLoaderRoute: typeof AuthenticatedPortalMeHistoryRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/favorites": {
      id: "/_authenticated/_portal/me/favorites";
      path: "/favorites";
      fullPath: "/me/favorites";
      preLoaderRoute: typeof AuthenticatedPortalMeFavoritesRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/channels": {
      id: "/_authenticated/_portal/me/channels";
      path: "/channels";
      fullPath: "/me/channels";
      preLoaderRoute: typeof AuthenticatedPortalMeChannelsRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/channel": {
      id: "/_authenticated/_portal/me/channel";
      path: "/channel";
      fullPath: "/me/channel";
      preLoaderRoute: typeof AuthenticatedPortalMeChannelRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/articles/$slug": {
      id: "/_authenticated/_portal/articles/$slug";
      path: "/$slug";
      fullPath: "/articles/$slug";
      preLoaderRoute: typeof AuthenticatedPortalArticlesSlugRouteImport;
      parentRoute: typeof AuthenticatedPortalArticlesRouteRoute;
    };
    "/_authenticated/_portal/me/articles": {
      id: "/_authenticated/_portal/me/articles";
      path: "/articles";
      fullPath: "/me/articles";
      preLoaderRoute: typeof AuthenticatedPortalMeArticlesRouteRouteImport;
      parentRoute: typeof AuthenticatedPortalMeRouteRoute;
    };
    "/_authenticated/_portal/me/articles/": {
      id: "/_authenticated/_portal/me/articles/";
      path: "/";
      fullPath: "/me/articles/";
      preLoaderRoute: typeof AuthenticatedPortalMeArticlesIndexRouteImport;
      parentRoute: typeof AuthenticatedPortalMeArticlesRouteRoute;
    };
    "/_authenticated/admin/articles/$id/edit": {
      id: "/_authenticated/admin/articles/$id/edit";
      path: "/$id/edit";
      fullPath: "/admin/articles/$id/edit";
      preLoaderRoute: typeof AuthenticatedAdminArticlesIdEditRouteImport;
      parentRoute: typeof AuthenticatedAdminArticlesRouteRoute;
    };
    "/_authenticated/_portal/media/$shortToken/edit": {
      id: "/_authenticated/_portal/media/$shortToken/edit";
      path: "/media/$shortToken/edit";
      fullPath: "/media/$shortToken/edit";
      preLoaderRoute: typeof AuthenticatedPortalMediaShortTokenEditRouteImport;
      parentRoute: typeof AuthenticatedPortalRoute;
    };
    "/_authenticated/_portal/me/articles/new": {
      id: "/_authenticated/_portal/me/articles/new";
      path: "/new";
      fullPath: "/me/articles/new";
      preLoaderRoute: typeof AuthenticatedPortalMeArticlesNewRouteImport;
      parentRoute: typeof AuthenticatedPortalMeArticlesRouteRoute;
    };
    "/_authenticated/_portal/me/articles/$token/edit": {
      id: "/_authenticated/_portal/me/articles/$token/edit";
      path: "/$token/edit";
      fullPath: "/me/articles/$token/edit";
      preLoaderRoute: typeof AuthenticatedPortalMeArticlesTokenEditRouteImport;
      parentRoute: typeof AuthenticatedPortalMeArticlesRouteRoute;
    };
  }
}

interface PortalHandleRouteChildren {
  PortalHandleSplatRoute: typeof PortalHandleSplatRoute;
  PortalHandleIndexRoute: typeof PortalHandleIndexRoute;
}

const PortalHandleRouteChildren: PortalHandleRouteChildren = {
  PortalHandleSplatRoute: PortalHandleSplatRoute,
  PortalHandleIndexRoute: PortalHandleIndexRoute,
};

const PortalHandleRouteWithChildren = PortalHandleRoute._addFileChildren(
  PortalHandleRouteChildren,
);

interface PortalRouteRouteChildren {
  PortalHandleRoute: typeof PortalHandleRouteWithChildren;
  PortalAboutRoute: typeof PortalAboutRoute;
  PortalBrowseRoute: typeof PortalBrowseRoute;
  PortalCookiesRoute: typeof PortalCookiesRoute;
  PortalExploreRoute: typeof PortalExploreRoute;
  PortalFeaturedRoute: typeof PortalFeaturedRoute;
  PortalLatestRoute: typeof PortalLatestRoute;
  PortalMembersRoute: typeof PortalMembersRoute;
  PortalPrivacyRoute: typeof PortalPrivacyRoute;
  PortalSearchRoute: typeof PortalSearchRoute;
  PortalTagsRoute: typeof PortalTagsRoute;
  PortalTermsRoute: typeof PortalTermsRoute;
  PortalTrendingRoute: typeof PortalTrendingRoute;
  PortalWatchRoute: typeof PortalWatchRoute;
  PortalIndexRoute: typeof PortalIndexRoute;
  PortalCIdRoute: typeof PortalCIdRoute;
  PortalPSlugRoute: typeof PortalPSlugRoute;
  PortalPlaylistTokenRoute: typeof PortalPlaylistTokenRoute;
  PortalUIdRoute: typeof PortalUIdRoute;
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalHandleRoute: PortalHandleRouteWithChildren,
  PortalAboutRoute: PortalAboutRoute,
  PortalBrowseRoute: PortalBrowseRoute,
  PortalCookiesRoute: PortalCookiesRoute,
  PortalExploreRoute: PortalExploreRoute,
  PortalFeaturedRoute: PortalFeaturedRoute,
  PortalLatestRoute: PortalLatestRoute,
  PortalMembersRoute: PortalMembersRoute,
  PortalPrivacyRoute: PortalPrivacyRoute,
  PortalSearchRoute: PortalSearchRoute,
  PortalTagsRoute: PortalTagsRoute,
  PortalTermsRoute: PortalTermsRoute,
  PortalTrendingRoute: PortalTrendingRoute,
  PortalWatchRoute: PortalWatchRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalCIdRoute: PortalCIdRoute,
  PortalPSlugRoute: PortalPSlugRoute,
  PortalPlaylistTokenRoute: PortalPlaylistTokenRoute,
  PortalUIdRoute: PortalUIdRoute,
};

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
);

interface AuthenticatedPortalArticlesRouteRouteChildren {
  AuthenticatedPortalArticlesSlugRoute: typeof AuthenticatedPortalArticlesSlugRoute;
  AuthenticatedPortalArticlesIndexRoute: typeof AuthenticatedPortalArticlesIndexRoute;
}

const AuthenticatedPortalArticlesRouteRouteChildren: AuthenticatedPortalArticlesRouteRouteChildren =
  {
    AuthenticatedPortalArticlesSlugRoute: AuthenticatedPortalArticlesSlugRoute,
    AuthenticatedPortalArticlesIndexRoute:
      AuthenticatedPortalArticlesIndexRoute,
  };

const AuthenticatedPortalArticlesRouteRouteWithChildren =
  AuthenticatedPortalArticlesRouteRoute._addFileChildren(
    AuthenticatedPortalArticlesRouteRouteChildren,
  );

interface AuthenticatedPortalMeArticlesRouteRouteChildren {
  AuthenticatedPortalMeArticlesNewRoute: typeof AuthenticatedPortalMeArticlesNewRoute;
  AuthenticatedPortalMeArticlesIndexRoute: typeof AuthenticatedPortalMeArticlesIndexRoute;
  AuthenticatedPortalMeArticlesTokenEditRoute: typeof AuthenticatedPortalMeArticlesTokenEditRoute;
}

const AuthenticatedPortalMeArticlesRouteRouteChildren: AuthenticatedPortalMeArticlesRouteRouteChildren =
  {
    AuthenticatedPortalMeArticlesNewRoute:
      AuthenticatedPortalMeArticlesNewRoute,
    AuthenticatedPortalMeArticlesIndexRoute:
      AuthenticatedPortalMeArticlesIndexRoute,
    AuthenticatedPortalMeArticlesTokenEditRoute:
      AuthenticatedPortalMeArticlesTokenEditRoute,
  };

const AuthenticatedPortalMeArticlesRouteRouteWithChildren =
  AuthenticatedPortalMeArticlesRouteRoute._addFileChildren(
    AuthenticatedPortalMeArticlesRouteRouteChildren,
  );

interface AuthenticatedPortalMeRouteRouteChildren {
  AuthenticatedPortalMeArticlesRouteRoute: typeof AuthenticatedPortalMeArticlesRouteRouteWithChildren;
  AuthenticatedPortalMeChannelRoute: typeof AuthenticatedPortalMeChannelRoute;
  AuthenticatedPortalMeChannelsRoute: typeof AuthenticatedPortalMeChannelsRoute;
  AuthenticatedPortalMeFavoritesRoute: typeof AuthenticatedPortalMeFavoritesRoute;
  AuthenticatedPortalMeHistoryRoute: typeof AuthenticatedPortalMeHistoryRoute;
  AuthenticatedPortalMeNotificationsRoute: typeof AuthenticatedPortalMeNotificationsRoute;
  AuthenticatedPortalMePlaylistsRoute: typeof AuthenticatedPortalMePlaylistsRoute;
  AuthenticatedPortalMeStyleGuideRoute: typeof AuthenticatedPortalMeStyleGuideRoute;
  AuthenticatedPortalMeUploadRoute: typeof AuthenticatedPortalMeUploadRoute;
  AuthenticatedPortalMeVideosRoute: typeof AuthenticatedPortalMeVideosRoute;
  AuthenticatedPortalMeIndexRoute: typeof AuthenticatedPortalMeIndexRoute;
}

const AuthenticatedPortalMeRouteRouteChildren: AuthenticatedPortalMeRouteRouteChildren =
  {
    AuthenticatedPortalMeArticlesRouteRoute:
      AuthenticatedPortalMeArticlesRouteRouteWithChildren,
    AuthenticatedPortalMeChannelRoute: AuthenticatedPortalMeChannelRoute,
    AuthenticatedPortalMeChannelsRoute: AuthenticatedPortalMeChannelsRoute,
    AuthenticatedPortalMeFavoritesRoute: AuthenticatedPortalMeFavoritesRoute,
    AuthenticatedPortalMeHistoryRoute: AuthenticatedPortalMeHistoryRoute,
    AuthenticatedPortalMeNotificationsRoute:
      AuthenticatedPortalMeNotificationsRoute,
    AuthenticatedPortalMePlaylistsRoute: AuthenticatedPortalMePlaylistsRoute,
    AuthenticatedPortalMeStyleGuideRoute: AuthenticatedPortalMeStyleGuideRoute,
    AuthenticatedPortalMeUploadRoute: AuthenticatedPortalMeUploadRoute,
    AuthenticatedPortalMeVideosRoute: AuthenticatedPortalMeVideosRoute,
    AuthenticatedPortalMeIndexRoute: AuthenticatedPortalMeIndexRoute,
  };

const AuthenticatedPortalMeRouteRouteWithChildren =
  AuthenticatedPortalMeRouteRoute._addFileChildren(
    AuthenticatedPortalMeRouteRouteChildren,
  );

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalArticlesRouteRoute: typeof AuthenticatedPortalArticlesRouteRouteWithChildren;
  AuthenticatedPortalMeRouteRoute: typeof AuthenticatedPortalMeRouteRouteWithChildren;
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute;
  AuthenticatedPortalSubscriptionsRoute: typeof AuthenticatedPortalSubscriptionsRoute;
  AuthenticatedPortalMediaShortTokenEditRoute: typeof AuthenticatedPortalMediaShortTokenEditRoute;
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalArticlesRouteRoute:
    AuthenticatedPortalArticlesRouteRouteWithChildren,
  AuthenticatedPortalMeRouteRoute: AuthenticatedPortalMeRouteRouteWithChildren,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalSubscriptionsRoute: AuthenticatedPortalSubscriptionsRoute,
  AuthenticatedPortalMediaShortTokenEditRoute:
    AuthenticatedPortalMediaShortTokenEditRoute,
};

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren);

interface AuthenticatedAdminArticlesRouteRouteChildren {
  AuthenticatedAdminArticlesNewRoute: typeof AuthenticatedAdminArticlesNewRoute;
  AuthenticatedAdminArticlesIndexRoute: typeof AuthenticatedAdminArticlesIndexRoute;
  AuthenticatedAdminArticlesIdEditRoute: typeof AuthenticatedAdminArticlesIdEditRoute;
}

const AuthenticatedAdminArticlesRouteRouteChildren: AuthenticatedAdminArticlesRouteRouteChildren =
  {
    AuthenticatedAdminArticlesNewRoute: AuthenticatedAdminArticlesNewRoute,
    AuthenticatedAdminArticlesIndexRoute: AuthenticatedAdminArticlesIndexRoute,
    AuthenticatedAdminArticlesIdEditRoute:
      AuthenticatedAdminArticlesIdEditRoute,
  };

const AuthenticatedAdminArticlesRouteRouteWithChildren =
  AuthenticatedAdminArticlesRouteRoute._addFileChildren(
    AuthenticatedAdminArticlesRouteRouteChildren,
  );

interface AuthenticatedAdminMediaRouteRouteChildren {
  AuthenticatedAdminMediaIdRoute: typeof AuthenticatedAdminMediaIdRoute;
  AuthenticatedAdminMediaIndexRoute: typeof AuthenticatedAdminMediaIndexRoute;
}

const AuthenticatedAdminMediaRouteRouteChildren: AuthenticatedAdminMediaRouteRouteChildren =
  {
    AuthenticatedAdminMediaIdRoute: AuthenticatedAdminMediaIdRoute,
    AuthenticatedAdminMediaIndexRoute: AuthenticatedAdminMediaIndexRoute,
  };

const AuthenticatedAdminMediaRouteRouteWithChildren =
  AuthenticatedAdminMediaRouteRoute._addFileChildren(
    AuthenticatedAdminMediaRouteRouteChildren,
  );

interface AuthenticatedAdminTranscodingRouteChildren {
  AuthenticatedAdminTranscodingProfilesRoute: typeof AuthenticatedAdminTranscodingProfilesRoute;
  AuthenticatedAdminTranscodingStatusRoute: typeof AuthenticatedAdminTranscodingStatusRoute;
}

const AuthenticatedAdminTranscodingRouteChildren: AuthenticatedAdminTranscodingRouteChildren =
  {
    AuthenticatedAdminTranscodingProfilesRoute:
      AuthenticatedAdminTranscodingProfilesRoute,
    AuthenticatedAdminTranscodingStatusRoute:
      AuthenticatedAdminTranscodingStatusRoute,
  };

const AuthenticatedAdminTranscodingRouteWithChildren =
  AuthenticatedAdminTranscodingRoute._addFileChildren(
    AuthenticatedAdminTranscodingRouteChildren,
  );

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArticlesRouteRoute: typeof AuthenticatedAdminArticlesRouteRouteWithChildren;
  AuthenticatedAdminMediaRouteRoute: typeof AuthenticatedAdminMediaRouteRouteWithChildren;
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute;
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute;
  AuthenticatedAdminChannelsRoute: typeof AuthenticatedAdminChannelsRoute;
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute;
  AuthenticatedAdminContentStructureRoute: typeof AuthenticatedAdminContentStructureRoute;
  AuthenticatedAdminDrmRoute: typeof AuthenticatedAdminDrmRoute;
  AuthenticatedAdminLiveRoomsRoute: typeof AuthenticatedAdminLiveRoomsRoute;
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute;
  AuthenticatedAdminPaymentRoute: typeof AuthenticatedAdminPaymentRoute;
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute;
  AuthenticatedAdminPlaylistsRoute: typeof AuthenticatedAdminPlaylistsRoute;
  AuthenticatedAdminPortalRoute: typeof AuthenticatedAdminPortalRoute;
  AuthenticatedAdminPromotionRoute: typeof AuthenticatedAdminPromotionRoute;
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute;
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute;
  AuthenticatedAdminStyleGuideRoute: typeof AuthenticatedAdminStyleGuideRoute;
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute;
  AuthenticatedAdminTranscodingRoute: typeof AuthenticatedAdminTranscodingRouteWithChildren;
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute;
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute;
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArticlesRouteRoute:
    AuthenticatedAdminArticlesRouteRouteWithChildren,
  AuthenticatedAdminMediaRouteRoute:
    AuthenticatedAdminMediaRouteRouteWithChildren,
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminChannelsRoute: AuthenticatedAdminChannelsRoute,
  AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
  AuthenticatedAdminContentStructureRoute:
    AuthenticatedAdminContentStructureRoute,
  AuthenticatedAdminDrmRoute: AuthenticatedAdminDrmRoute,
  AuthenticatedAdminLiveRoomsRoute: AuthenticatedAdminLiveRoomsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPaymentRoute: AuthenticatedAdminPaymentRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPlaylistsRoute: AuthenticatedAdminPlaylistsRoute,
  AuthenticatedAdminPortalRoute: AuthenticatedAdminPortalRoute,
  AuthenticatedAdminPromotionRoute: AuthenticatedAdminPromotionRoute,
  AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStyleGuideRoute: AuthenticatedAdminStyleGuideRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminTranscodingRoute:
    AuthenticatedAdminTranscodingRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
};

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren);

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute;
  AuthenticatedSettingsPasswordRoute: typeof AuthenticatedSettingsPasswordRoute;
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute;
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute;
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsPasswordRoute: AuthenticatedSettingsPasswordRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
};

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren;
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren;
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
